#!/bin/bash
#Hashes all files in /boot to check them during early boot
#Exit codes: 0 = success, 1 = checksum mbr mismatch, 2 = checksum /boot mismatch,
#3 = checksum mbr/boot mismatch, 4 = not root, 5 = no hasher found, 6 = wrong usage,
#7 = write error, 8 = dd error, 9 = file not found

###################################################################################
# "THE HUG-WARE LICENSE" (Revision 1):                                            #
# xo <xo@rotce.de> and tastytea <tastytea@tastytea.de> wrote these files. As long #
# as you retain this notice you can do whatever you want with this stuff. If we   #
# meet some day, and you think this stuff is worth it, you can give us a hug.     #
###################################################################################

VERSION="0.8.0"
PATH="/bin:/usr/bin:/sbin:/usr/sbin:${PATH}"

DIGEST_FILE="/var/lib/hashboot.digest"
DIGEST_FILE_TMP="/tmp/hashboot.digesttmp"
LOG_FILE="/tmp/hashboot.log"
MBR_DEVICE="/dev/sda"
MBR_SIZE=1024
MBR_TMP="/tmp/mbr"
BACKUP_FILE="/var/cache/boot-backup.tar"
HASHER=""
BOOT_MOUNTED=0
CONFIG_FILE="/etc/hashboot.cfg"
COUNTER=0
DD_STATUS="none"

#Umount /boot if we mounted it, exit with given exit code
die ()
{
    if [ ${BOOT_MOUNTED} -gt 0 ]
    then
        umount /boot
    fi

    [ -z "${2}" ] || echo "${2}" >&2
    exit ${1}
}

write_hashes ()
{
    #Write header to ${1}
    echo "#hashboot ${VERSION} - Algorithm: $(basename ${HASHER})" > ${1}
    #Write MBR of MBR_DEVICE to ${1}
    dd if=${MBR_DEVICE} of=${MBR_TMP} bs=${MBR_SIZE}K count=1 status=${DD_STATUS} || die 8
    #Write hashes of all regular files to ${1}
    ${HASHER} ${MBR_TMP} >> ${1}
    find /boot -type f -exec ${HASHER} --binary {} >> ${1} +
}
    
#If we're not root: exit
if [ ${UID} -ne 0 ]
then
    die 4 "You have to be root"
fi

#If /boot is in fstab but not mounted: mount, mark as mounted
if grep -q '/boot' /etc/fstab && ! grep -q /boot /etc/mtab
then
    mount /boot
    BOOT_MOUNTED=1
fi

# Debian < 8 check
if which lsb_release > /dev/null && [ "$(lsb_release -si)" == "Debian" ] && [ $(lsb_release -sr | cut -d'.' -f1) -lt 8 ]
then
        DD_STATUS="noxfer"
fi

#Look for config file and set ${MBR_DEVICE}.
if [ -f ${CONFIG_FILE} ]
then
    source ${CONFIG_FILE} || die 9 "Error reading config file"
#If not found, create one and ask for ${MBR_DEVICE}
else
    #Create ${CONFIG_FILE} with defaults if noninterctive
    if [ -t "0" ]
    then
        echo -n "Which device contains the MBR? [/dev/sda] "
        read -r MBR_DEVICE
        [ -z "${MBR_DEVICE}" ] && MBR_DEVICE="/dev/sda"
        echo "#Device with the MBR on it" > ${CONFIG_FILE}
        echo "MBR_DEVICE=${MBR_DEVICE}" >> ${CONFIG_FILE}
    
        echo -n "Where should backup file be stored? [/var/cache/boot-backup.tar] " 
        read -r BACKUP_FILE
        [ -z "${BACKUP_FILE}" ] && BACKUP_FILE="/var/cache/boot-backup.tar"
        echo "#Where the Backup files are stored" >> ${CONFIG_FILE}
        echo "BACKUP_FILE=${BACKUP_FILE}" >> ${CONFIG_FILE}
    else
        echo "#Device with the MBR on it" > ${CONFIG_FILE}
        echo "MBR_DEVICE=${MBR_DEVICE}" >> ${CONFIG_FILE}
        echo "#Where the Backup files are stored" >> ${CONFIG_FILE}
        echo "BACKUP_FILE=${BACKUP_FILE}" >> ${CONFIG_FILE}
    fi
fi

# Find out where the first partition starts and set ${MBR_SIZE} in KiB
sectorsize=$(LC_ALL=C fdisk -l ${MBR_DEVICE} | grep '^Units' | awk '{print $8}' )
if [ "${sectorsize}" == "=" ] # Older versions of util-linux
then
    sectorsize=$(LC_ALL=C fdisk -l ${MBR_DEVICE} | grep '^Units' | awk '{print $9}' )
fi
startsector=$(LC_ALL=C fdisk -l ${MBR_DEVICE} | grep -A1 'Device' | tail -n1 | awk '{print $2}' )
if [ "${startsector}" == "*" ] # If partition is marked as boot, read next field
then
    startsector=$(LC_ALL=C fdisk -l ${MBR_DEVICE} | grep -A1 'Device' | tail -n1 | awk '{print $3}' )
fi

MBR_SIZE=$(expr ${sectorsize} \* ${startsector} / 1024)

if [ ${?} != 0 ]
then
    echo "Something went wrong. Most likely your partition table is corrupt." >&2
    die 1 "You have to recover the MBR manually by copying the mbr from ${BACKUP_FILE}"
fi

if [ "${1}" == "index" ]
then
    #Try different hashers, use the most secure
    HASHER=$(/usr/bin/which sha512sum 2> /dev/null)
    test -z "${HASHER}" && HASHER=$(/usr/bin/which sha384sum 2> /dev/null)
    test -z "${HASHER}" && HASHER=$(/usr/bin/which sha256sum 2> /dev/null)
    test -z "${HASHER}" && HASHER=$(/usr/bin/which sha224sum 2> /dev/null)
    #It gets insecure below here, but better than nothing?
    test -z "${HASHER}" && HASHER=$(/usr/bin/which sha1sum 2> /dev/null)
    test -z "${HASHER}" && HASHER=$(/usr/bin/which md5sum 2> /dev/null)
    #If we found no hasher: exit
    [ -z "${HASHER}" ] && die 5 "No hash calculator found"
    
    #Exists ${DIGEST_FILE}, if true run do magic, else write ${DIGEST_FILE}
    if [ -f ${DIGEST_FILE} ]
    then

        #Collect mbr and /boot hashes and write to $DIGEST_FILE_TMP
        write_hashes $DIGEST_FILE_TMP

        #Compare $DIGEST_FILE_TMP against ${DIGEST_FILE} and exit, when fine. Otherwise do magic.
        if diff -q --ignore-matching-lines='#hashboot' ${DIGEST_FILE} ${DIGEST_FILE_TMP} ;
        then
            die 0
        else
            for file in $(diff ${DIGEST_FILE} ${DIGEST_FILE_TMP} | grep -v '#hashboot' | grep '<' | cut -d'*' -f2 | sed 's/\ /\\ /g' ); 
            do 
                #lösche_aus_tar
                tar --delete -v -P -f $BACKUP_FILE $file
            done
            for file in $(diff ${DIGEST_FILE} ${DIGEST_FILE_TMP} | grep -v '#hashboot' | grep '>' | cut -d'*' -f2 | sed 's/\ /\\ /g' );
            do
                tar -r -v -P -f $BACKUP_FILE $file
            done
        fi
    #nur, wenn das updaten des Backups geklappt hat. *im Hinterkopf behalt*
    mv ${DIGEST_FILE_TMP} ${DIGEST_FILE}
    else
        write_hashes $DIGEST_FILE
        tar -cpPf ${BACKUP_FILE} ${MBR_TMP} /boot ${DIGEST_FILE} || die 7 "Error writing ${BACKUP_FILE}"
        echo "Backup written to ${BACKUP_FILE}"
    fi
 
elif [ "${1}" == "check" ]
then
    [ -f ${DIGEST_FILE} ] || die 9 "No digestfile"
    HASHER=$(head -n1 ${DIGEST_FILE} | awk '{print $5}')
    dd if=${MBR_DEVICE} of=${MBR_TMP} bs=${MBR_SIZE}K count=1 status=${DD_STATUS} || die 8
    if ! grep ${MBR_TMP} ${DIGEST_FILE} | ${HASHER} --check --warn --quiet --strict | tee ${LOG_FILE}
    then
        echo "    !! TIME TO PANIK: MBR WAS MODIFIED !!"
        COUNTER=$((COUNTER + 1))
    fi
    if ! grep -v ${MBR_TMP} ${DIGEST_FILE} | ${HASHER} --check --warn --quiet --strict | tee -a ${LOG_FILE}
    then
        echo "    !! TIME TO PANIK: AT LEAST 1 FILE WAS MODIFIED !!"
        COUNTER=$((COUNTER + 2))
        die $COUNTER
    fi
elif [ "${1}" == "recover" ]
then
    echo "Restoring files from backup... (type yes or no for each file)"

    #For each failed file: ask if it should be recovered from backup
    for file in $(cut -d: -f1 ${LOG_FILE})
    do
        tar -xpPvwf ${BACKUP_FILE} ${file}
        [ $? != 0 ] && echo "Error restoring ${file} from backup, continuing" >&2
        #If the MBR is to be recovered, copy to ${MBR_DEVICE}
        if [ "${file}" == ${MBR_TMP} ]
        then
            cp ${MBR_TMP} ${MBR_DEVICE}
            [ $? != 0 ] && echo "Error restoring MBR from backup, continuing" >&2
        fi
    done
else
    die 6 "Usage: ${0} index|check|recover"
fi

die 0
